#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.education.supplier.model
  mapperLocations: classpath:mapper/*.xml


---

server:
  port: 8888

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/union?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource


# PageHelper配置
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: true
  returnPageInfo: true
  params: count=countSql

thymeleaf:
  cache: false
  mode: LEGACYHTML5